SET SERVEROUTPUT ON;

DECLARE
	TYPE TEST_TABLE_TYP IS TABLE OF VARCHAR2(100) INDEX BY VARCHAR(100);
	TEST_TABLE TEST_TABLE_TYP ;
  KEY_STR VARCHAR(100);
BEGIN
  TEST_TABLE('A1') := 'A1 DATA';
  TEST_TABLE('A2') := 'A2 DATA';
  TEST_TABLE('A3') := 'A3 DATA';
  TEST_TABLE('A4') := 'A4 DATA';
  
  KEY_STR := TEST_TABLE.FIRST;
  WHILE KEY_STR IS NOT NULL LOOP
    DBMS_OUTPUT.PUT_LINE(TEST_TABLE(KEY_STR));
    KEY_STR := TEST_TABLE.NEXT(KEY_STR);
  END LOOP;
  
END;