SET SERVEROUTPUT ON;

DECLARE
	TYPE TEST_REC_TYP IS RECORD(FIELD1 NUMBER, FIELD2 VARCHAR2(100));
	TEST_REC1 TEST_REC_TYP;
BEGIN
	TEST_REC1.FIELD1 := 1;
	TEST_REC1.FIELD2 := 'TEST RECORD';
	DBMS_OUTPUT.PUT_LINE(TEST_REC1.FIELD1 || ': ' || TEST_REC1.FIELD2);
END;