/*
	The Table Relation in Oracle Database is described by Contraints. 
	The Constraints would include:
	* Primary Key Constraints
	* Foreign Key Constraints
	
	The below would provide SQL for query related tables for given table
*/

-- The SQL would query the dependent tables of given table
SELECT TABLE_NAME, 
  (SELECT P.TABLE_NAME FROM USER_CONSTRAINTS P WHERE CONSTRAINT_TYPE = 'P' AND P.CONSTRAINT_NAME = R.R_CONSTRAINT_NAME) AS DEPEND_TABLE
  FROM USER_CONSTRAINTS R
WHERE 
  CONSTRAINT_TYPE = 'R' 
  AND TABLE_NAME LIKE '%&TABLE_NAME%'
;

-- The SQL would query the tables would depends on the given table
SELECT P.TABLE_NAME, R.TABLE_NAME AS REQUIRE_TABLE 
FROM USER_CONSTRAINTS R 
JOIN (  SELECT TABLE_NAME, CONSTRAINT_NAME
  FROM USER_CONSTRAINTS P
  WHERE P.CONSTRAINT_TYPE = 'P'
  AND TABLE_NAME LIKE '%&TABLE_NAME%') P
ON P.CONSTRAINT_NAME = R.R_CONSTRAINT_NAME
; 

-- The SQL would query the related table and specify the relation type, REQUIRE and DEPEND
SELECT TABLE_NAME AS QUERY_TABLE, 
  (SELECT P.TABLE_NAME FROM USER_CONSTRAINTS P WHERE CONSTRAINT_TYPE = 'P' AND P.CONSTRAINT_NAME = R.R_CONSTRAINT_NAME) AS REL_TABLE,
  'DEPEND' AS REL_TYPE
  FROM USER_CONSTRAINTS R
WHERE 
  CONSTRAINT_TYPE = 'R' 
  AND TABLE_NAME LIKE '%&TABLE_NAME%'
UNION 
SELECT P.TABLE_NAME AS QUERY_TABLE, R.TABLE_NAME AS REL_TABLE, 'REQUIRE' AS REL_TYPE
FROM USER_CONSTRAINTS R 
JOIN (  SELECT TABLE_NAME, CONSTRAINT_NAME
  FROM USER_CONSTRAINTS P
  WHERE P.CONSTRAINT_TYPE = 'P'
  AND TABLE_NAME LIKE '%&TABLE_NAME%') P
ON P.CONSTRAINT_NAME = R.R_CONSTRAINT_NAME
ORDER BY REL_TYPE
;