-- Merge statement is to select row from onr or more source for update or insert into a table or view.

SET SERVEROUTPUT ON;

CREATE TABLE TABLE1 (
COL1 VARCHAR2(100),
COL2 VARCHAR2(100),
COL3 VARCHAR2(100),
COL4 VARCHAR2(100),
COL5 VARCHAR2(100)
)

INSERT INTO TABLE1 (COL1, COL2, COL3, COL4, COL5) VALUES ('VALUE1', 'VALUE1', 'VALUE1', 'VALUE1', 'VALUE1');
INSERT INTO TABLE1 (COL1, COL2, COL3, COL4, COL5) VALUES ('VALUE2', 'VALUE2', 'VALUE2', 'VALUE2', 'VALUE2');
INSERT INTO TABLE1 (COL1, COL2, COL3, COL4, COL5) VALUES ('VALUE3', 'VALUE3', 'VALUE3', 'VALUE3', 'VALUE3');
INSERT INTO TABLE1 (COL1, COL2, COL3, COL4, COL5) VALUES ('VALUE4', 'VALUE4', 'VALUE4', 'VALUE4', 'VALUE4');
INSERT INTO TABLE1 (COL1, COL2, COL3, COL4, COL5) VALUES ('VALUE5', 'VALUE5', 'VALUE5', 'VALUE5', 'VALUE5');

-- THIS SQL WOULD UPDATE COL5 AS 'UPDATE' 
-- AND IT WOULD INSERT RECORD AS SPECIFIED AFTER UNION STATEMENT
MERGE INTO TABLE1 A USING (
	SELECT COL1, COL2, COL3, COL4, 'UPDATE' AS COL5 FROM TABLE1 
	UNION 
	SELECT 'INSERT1', 'INSERT1', 'INSERT1', 'INSERT1', 'INSERT1' FROM DUAL
	) B 
ON (A.COL1 = B.COL1) 
WHEN MATCHED  THEN UPDATE SET A.COL5 = B.COL5
WHEN NOT MATCHED  THEN INSERT (COL1, COL2, COL3, COL4, COL5) 
	VALUES (B.COL1, B.COL2, B.COL3, B.COL4, B.COL5)
	WHERE B.COL1 = 'INSERT1'
;

SELECT * FROM TABLE1;

-- VALUE1	VALUE1	VALUE1	VALUE1	UPDATE
-- VALUE2	VALUE2	VALUE2	VALUE2	UPDATE
-- VALUE3	VALUE3	VALUE3	VALUE3	UPDATE
-- VALUE4	VALUE4	VALUE4	VALUE4	UPDATE
-- VALUE5	VALUE5	VALUE5	VALUE5	UPDATE
-- INSERT1	INSERT1	INSERT1	INSERT1	INSERT1

DROP TABLE TABLE1;