SELECT * FROM USER_TABLES;
SELECT * FROM USER_CONSTRAINTS;
SELECT * FROM USER_CONS_COLUMNS;
SELECT * FROM USER_INDEXES;
SELECT * FROM USER_IND_COLUMNS;
SELECT * FROM USER_OBJECTS WHERE OBJECT_TYPE = 'FUNCTION';
SELECT * FROM USER_SOURCE WHERE TYPE = 'FUNCTION';